### ISSUE TITLE
Chapter selector not working as intented

### ISSUE THREAD

**Issue by CornHusker89** [smallketchup82/rezero-summarizer#18]
reproduction instructions:
use the command `python main.py -c 1,2 -i <filepath-to-arc-six> -v`
(you can also negate the `-c 1,2`, and instead select those chapters with the other method, and get the same result)

it will summarize arc 6 chapter 31 as if it were another part within chapter one

![image](https://github.com/smallketchup82/rezero-summarizer/assets/137812325/41d8d300-c236-4473-b3bb-5829ea2c05df)

**Comment by smallketchup82** [comment]
Fixed in 8b75270
