### ISSUE TITLE
Remove unused variable actualchapter

### ISSUE THREAD

**Issue by smallketchup82** [smallketchup82/rezero-summarizer#35]
Linter reports the variable at [line 186 of main.py](https://github.com/smallketchup82/rezero-summarizer/blob/1eb71d16467ed9c13a702421f54308f70f7e5166/main.py#L186C31-L186C31) as being unused. consider removing it

**Comment by CornHusker89** [comment]
removed in https://github.com/smallketchup82/rezero-summarizer/commit/842392d7be85f9610cf3db2b1ada53fde15881c9
