### ISSUE TITLE
Downloader.py not running unless the arcs argument is passed

### ISSUE THREAD

**Issue by smallketchup82** [smallketchup82/rezero-summarizer#41]
**Describe the bug**
downloader.py refuses to run with `-l` because `arcs` is a required positional argument

**To Reproduce**
1. Run downloader.py with -l

To fix, change `arcs` to be a `--` argument instead of positional

**Comment by smallketchup82** [comment]
@CornHusker89 high prio

**Comment by CornHusker89** [comment]
fixed in https://github.com/smallketchup82/rezero-summarizer/commit/cb70f045feabea598d9b531cd6cc12aa2c8025ea
